### PR TITLE
update recipe

### PR DESCRIPTION
**Pull request by clementchadebec**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by clementchadebec** [comment]
@conda-forge-admin, please rerender

**Comment by clementchadebec** [comment]
@conda-forge-admin, please add bot automerge

**Comment by clementchadebec** [comment]
Hi @sugatoray,

Can you please merge this PR ? I do not have the right permissions to do so. I have fixed some issues in the dependencies further to the changes in the latest release and changed the maintainer of the feedstock to ease further releases.

Thanks in advance!

Best,

Clément

**Comment by sugatoray** [comment]
@clementchadebec Thank you for the PR and adding yourself as a maintainer.

**Comment by sugatoray** [comment]
@clementchadebec I see that I was removed from this repository as a co-maintainer. Could you please add me back in? Thank you.

**Pull request merged**
